# Generated by Django 4.0.3 on 2022-03-18 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='departamaneto',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='sueldo',
        ),
    ]
