# Generated by Django 4.0.3 on 2022-03-18 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtto', '0002_remove_empleado_cargo_remove_empleado_departamaneto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='cedula',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
